<?php

/**
 * @file
 * Primary module hooks for Neo | Alchemist module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\ContentEntityTypeInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Url;
use Drupal\field\FieldConfigInterface;
use Drupal\field\FieldStorageConfigInterface;
use Drupal\media_library\MediaLibraryState;
use Drupal\neo_alchemist\Form\InstanceComponentDeleteForm;
use Drupal\neo_alchemist\Form\InstanceComponentForm;
use Drupal\neo_alchemist\Form\InstanceComponentPublishForm;
use Drupal\neo_alchemist\Form\InstanceComponentResetForm;
use Drupal\neo_alchemist\Form\InstanceComponentRevertForm;
use Drupal\neo_alchemist\Form\InstanceComponentSortForm;
use Drupal\neo_tooltip\Tooltip;

/**
 * Implements hook_theme().
 */
function neo_alchemist_theme(): array {
  return [
    'html__neo_alchemist' => [
      'base hook' => 'html',
    ],
    'field__neo_component_tree' => [
      'base hook' => 'field',
    ],
    'neo_alchemist_entity' => [
      'render element' => 'elements',
    ],
    'neo_alchemist_manage' => [
      'variables' => [
        'id' => '',
        'iframe_url' => '',
        'iframe_start' => [],
        'iframe_end' => [],
        'form' => [],
        'form_position' => 'footer',
        'top_start' => [],
        'top_end' => [],
        'bottom_start' => [],
        'bottom_end' => [],
      ],
    ],
    'neo_alchemist_overlay' => [
      'variables' => [],
    ],
    'neo_alchemist_component_preview' => [
      'render element' => 'elements',
    ],
    'neo_alchemist_library' => [
      'variables' => [
        'components' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for page__neo_alchemist_preview.
 */
function neo_alchemist_preprocess_html__neo_alchemist(&$variables) {
  // kint($variables);
  // die;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for html.
 */
function neo_alchemist_theme_suggestions_html_alter(array &$suggestions, array $variables) {
  if ($variables['html']['#is_alchemist'] ?? FALSE) {
    $suggestions = ['html__neo_alchemist'];
  }
}

/**
 * Implements hook_preprocess_HOOK() for neo_alchemist_manage.
 */
function template_preprocess_neo_alchemist_manage(&$variables) {
  $iframeUrl = $variables['iframe_url'] ?? '';
  if ($iframeUrl) {
    $sizes = ['desktop', 'tablet', 'mobile'];
    $options = $iframeUrl->getOptions();
    $options['query']['id'] = $variables['id'] ?? '';
    foreach ($sizes as $size) {
      $options['query']['size'] = $size;
      $iframeUrl->setOptions($options);
      $variables["src_$size"] = $iframeUrl->toString();
    }
  }
}

/**
 * Implements hook_preprocess_HOOK() for neo_alchemist_component_preview.
 */
function template_preprocess_neo_alchemist_component_preview(&$variables) {
  $variables['content'] = [];
  $elements = $variables['elements'];
  foreach (Element::children($elements) as $child) {
    $variables['content'][$child] = $elements[$child];
  }
  $size = \Drupal::request()->query->get('size');
  if ($size) {
    $variables['attributes']['data-size'] = $size;
  }
}

/**
 * Implements hook_preprocess_HOOK() for neo_alchemist_overlay.
 */
function template_preprocess_neo_alchemist_overlay(&$variables) {
  $tooltip = new Tooltip('Close');
  $variables['close'] = [
    '#type' => 'link',
    '#title' => neo_admin_icon('Close', 'times')->iconOnly(),
    '#url' => Url::fromRoute('<current>'),
    '#attributes' => [
      'class' => ['close', 'btn', 'btn-xs'],
    ],
  ];
  $tooltip->applyTo($variables['close']);

  $variables['ops'] = [];
  foreach ([
    'edit' => t('Edit'),
    'sort' => t('Sort'),
    'clone' => t('Clone'),
    'delete' => t('Delete'),
  ] as $op => $label) {
    $tooltip = new Tooltip($label);
    $tooltip->setPlacementToTop();
    $variables['ops'][$op] = [
      '#type' => 'link',
      '#title' => neo_admin_icon($label)->iconOnly(),
      '#url' => Url::fromRoute('<current>'),
      '#attributes' => [
        'class' => ['op', 'btn', 'btn-xs'],
        'data-op' => $op,
      ],
    ];
    $tooltip->applyTo($variables['ops'][$op]);
  }

  $label = t('Add Component Before');
  $tooltip = new Tooltip($label);
  $tooltip->setPlacementToTop();
  $variables['op_add_before'] = [
    '#type' => 'link',
    '#title' => neo_admin_icon($label, 'plus')->iconOnly(),
    '#url' => Url::fromRoute('<current>'),
    '#attributes' => [
      'class' => ['op'],
      'data-op' => 'add-before',
    ],
  ];
  $tooltip->applyTo($variables['op_add_before']);

  $label = t('Add Component After');
  $tooltip = new Tooltip($label);
  $tooltip->setPlacementToBottom();
  $variables['op_add_after'] = [
    '#type' => 'link',
    '#title' => neo_admin_icon($label, 'plus')->iconOnly(),
    '#url' => Url::fromRoute('<current>'),
    '#attributes' => [
      'class' => ['op'],
      'data-op' => 'add-after',
    ],
  ];
  $tooltip->applyTo($variables['op_add_after']);
}

/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 *
 * @see \Drupal\neo_alchemist\MediaLibraryXbPropOpener
 */
function neo_alchemist_field_widget_single_element_media_library_widget_form_alter(array &$form, FormStateInterface $form_state, array $context): void {
  // Use an XB-specific media library opener, because the default opener assumes
  // the media library is opened for a field widget of a field instance on the
  // host entity type. That is not true for XB's "static prop sources".
  // @see \Drupal\neo_alchemist\PropSource\StaticPropSource
  // @see \Drupal\neo_alchemist\Form\ComponentPropsForm::buildForm()
  if ($form_state->get('neo_component_form') !== TRUE) {
    return;
  }

  // @see \Drupal\media_library\Plugin\Field\FieldWidget\MediaLibraryWidget::formElement()
  assert(array_key_exists('open_button', $form));
  assert(array_key_exists('#media_library_state', $form['open_button']));
  $old = $form['open_button']['#media_library_state'];
  assert($old instanceof MediaLibraryState);
  $form['open_button']['#media_library_state'] = MediaLibraryState::create(
    'neo_alchemist.media_library.opener',
    $old->getAllowedTypeIds(),
    $old->getSelectedTypeId(),
    $old->getAvailableSlots(),
    [
      // This single opener parameter is necessary.
      // @see \Drupal\neo_alchemist\MediaLibraryXbPropOpener::getSelectionResponse()
      'field_widget_id' => $old->getOpenerParameters()['field_widget_id'],
    ]
  );
}

/**
 * Implements hook_entity_type_alter().
 */
function neo_alchemist_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  $configFactory = \Drupal::configFactory();
  foreach ($entity_types as $entityType) {
    if ($entityType instanceof ContentEntityTypeInterface) {
      $entityTypeId = $entityType->id();
      $names = $configFactory->listAll('field.field.' . $entityTypeId);
      foreach ($configFactory->loadMultiple($names) as $config) {
        if ($config->get('field_type') === 'neo_component_tree') {
          $baseRoute = NULL;
          if ($entityType->hasLinkTemplate('canonical')) {
            $baseRoute = $entityType->getLinkTemplate('canonical');
          }
          elseif ($entityType->hasLinkTemplate('edit-form')) {
            $baseRoute = $entityType->getLinkTemplate('edit-form');
          }
          if ($baseRoute) {
            $entityType->setLinkTemplate('alchemist', $baseRoute . '/alchemist');
            $entityType->setLinkTemplate("alchemist.manage", "$baseRoute/alchemist/{neo_field}");
            $entityType->setLinkTemplate("alchemist.preview", "$baseRoute/alchemist/{neo_field}/preview");
            $entityType->setLinkTemplate("alchemist.library", "$baseRoute/alchemist/{neo_field}/library");
            $entityType->setLinkTemplate("alchemist.publish", "$baseRoute/alchemist/{neo_field}/publish");
            $entityType->setLinkTemplate("alchemist.revert", "$baseRoute/alchemist/{neo_field}/revert");
            $entityType->setLinkTemplate("alchemist.reset", "$baseRoute/alchemist/{neo_field}/reset");
            $entityType->setLinkTemplate("alchemist.sort", "$baseRoute/alchemist/{neo_field}/sort");
            $entityType->setLinkTemplate("alchemist.add", "$baseRoute/alchemist/{neo_field}/add/{neo_component}");
            $entityType->setLinkTemplate("alchemist.edit", "$baseRoute/alchemist/{neo_field}/edit/{neo_component}");
            $entityType->setLinkTemplate("alchemist.clone", "$baseRoute/alchemist/{neo_field}/clone/{neo_component}");
            $entityType->setLinkTemplate("alchemist.delete", "$baseRoute/alchemist/{neo_field}/delete/{neo_component}");
            $entityType->setFormClass('alchemist', InstanceComponentForm::class);
            $entityType->setFormClass('alchemist_publish', InstanceComponentPublishForm::class);
            $entityType->setFormClass('alchemist_revert', InstanceComponentRevertForm::class);
            $entityType->setFormClass('alchemist_reset', InstanceComponentResetForm::class);
            $entityType->setFormClass('alchemist_sort', InstanceComponentSortForm::class);
            $entityType->setFormClass('alchemist_edit', InstanceComponentForm::class);
            $entityType->setFormClass('alchemist_delete', InstanceComponentDeleteForm::class);
          }
          break;
        }
      }
    }
  }
}

/**
 * Implements hook_entity_insert().
 */
function neo_alchemist_entity_insert(EntityInterface $entity) {
  if ($entity instanceof FieldStorageConfigInterface && $entity->getType() === 'neo_component_tree') {
    \Drupal::state()->set('neo_alchemist.rebuild_needed', TRUE);
  }
}

/**
 * Implements hook_entity_delete().
 */
function neo_alchemist_entity_delete(EntityInterface $entity) {
  if ($entity instanceof FieldStorageConfigInterface && $entity->getType() === 'neo_component_tree') {
    \Drupal::state()->set('neo_alchemist.rebuild_needed', TRUE);
  }
}

/**
 * Implements hook_alchemist_entity_bundle_field_info_alter().
 */
function neo_alchemist_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  // Alter the field config entity to use a custom class for component tree
  // fields.
  foreach ($fields as $id => $field) {
    /** @var \Drupal\Core\Field\Fiel $field */
    if ($field instanceof FieldConfigInterface && $field->getType() === 'neo_component_tree') {
      $entity_class = 'Drupal\neo_alchemist\Entity\ComponentFieldConfig';
      $instance = new $entity_class($field->toArray(), 'field_config');
      $fields[$id] = $instance;
    }
  }
}

/**
 * Implements hook_entity_operation().
 */
function neo_alchemist_entity_operation(EntityInterface $entity) {
  $operations = [];
  if ($entity->hasLinkTemplate('alchemist')) {
    $operations['alchemist'] = [
      'title' => t('Layout'),
      'url' => $entity->toUrl('alchemist'),
      'weight' => 50,
    ];
  }
  else {
    $info = $entity->getEntityType();
    // Add manage fields and display links if this entity type is the bundle
    // of another and that type has field UI enabled.
    if (($bundle_of = $info->getBundleOf()) && \Drupal::entityTypeManager()->getDefinition($bundle_of)->getLinkTemplate('alchemist')) {
      $url = Url::fromRoute("entity.{$bundle_of}.field_ui.alchemist", [
        $entity->getEntityTypeId() => $entity->id(),
      ]);
      if ($url->access()) {
        $operations['alchemist'] = [
          'title' => t('Manage Layout'),
          'weight' => 0,
          'url' => $url,
        ];
      }
    }
  }
  return $operations;
}

/**
 * Implements hook_preprocess_block().
 */
function neo_alchemist_preprocess_block(&$variables) {
  if ($variables['base_plugin_id'] !== 'page_title_block') {
    return;
  }
  if (neo_alchemist_route_is_alchemist()) {
    $variables['attributes']['class'][] = 'sr-only';
  }
}

/**
 * Implements hook_preprocess_region__content().
 */
function neo_alchemist_preprocess_region__content(&$variables) {
  $variables['alchemist'] = FALSE;
  if (neo_alchemist_route_is_alchemist()) {
    $variables['alchemist'] = TRUE;
  }
}

/**
 * Prepares variables for product templates.
 *
 * Default template: commerce-product.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing rendered fields.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_neo_alchemist_entity(array &$variables) {
  $variables['tag'] = $variables['elements']['#tag'] ?? '';
  foreach (Element::children($variables['elements']) as $key) {
    // Only add alchemist fields.
    if (!empty($variables['elements'][$key]['#field_type']) && $variables['elements'][$key]['#field_type'] === 'neo_component_tree') {
      $variables['content'][$key] = $variables['elements'][$key];
    }
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function neo_alchemist_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // We consider only fieldable fields.
  $fieldableFields = array_filter($build, function ($key) {
    return substr($key, 0, 6) === 'field_';
  }, ARRAY_FILTER_USE_KEY);
  // If we only have one fieldable field and it is a component tree field, we
  // render the entity using the neo_alchemist_entity theme.
  if (count($fieldableFields) === 1) {
    $isAlchemistField = !empty(array_filter($fieldableFields, function ($field) {
      return isset($field['#field_type']) && $field['#field_type'] === 'neo_component_tree';
    }));
    if ($isAlchemistField) {
      $build['#tag'] = '';
      if (!empty($build['#attributes'] ?? [])) {
        $build['#tag'] = 'div';
      }
      $build['#theme'] = 'neo_alchemist_entity';
    }
  }
}

/**
 * Check if route is alchemist-enabled route.
 *
 * @return bool
 *   TRUE if the route is an alchemist-enabled route.
 */
function neo_alchemist_route_is_alchemist() {
  $isAlchemistRoute = &drupal_static(__FUNCTION__);
  if (isset($isAlchemistRoute)) {
    return $isAlchemistRoute;
  }
  $isAlchemistRoute = FALSE;
  $routeMatch = \Drupal::routeMatch();
  $routeObject = $routeMatch->getRouteObject();
  $entityTypeId = $routeObject->getOption('_neo_alchemist');
  if (!$entityTypeId) {
    return;
  }
  $entityView = $routeObject->getDefault('_entity_view') ?? $entityTypeId . '.default';
  [, $viewModeId] = explode('.', $entityView);
  if ($entity = $routeMatch->getParameter($entityTypeId)) {
    $bundle = $entity->bundle();
    $viewModeId = $viewModeId === 'full' ? 'default' : $viewModeId;
    $viewMode = \Drupal::service('entity_type.manager')
      ->getStorage('entity_view_display')
      ->load($entityTypeId . '.' . $bundle . '.' . $viewModeId);
    if ($viewMode) {
      foreach ($viewMode->getComponents() as $field_name => $component) {
        if (($component['type'] ?? '') === 'neo_component_tree') {
          $isAlchemistRoute = TRUE;
          break;
        }
      }
    }
  }
  return $isAlchemistRoute;
}

/**
 * Implements hook_config_schema_info_alter().
 */
function neo_alchemist_config_schema_info_alter(&$definitions) {
  if (isset($definitions['block_settings'])) {
    foreach ($definitions as $key => $definition) {
      if (($definition['type'] ?? NULL) === 'block_settings') {
        $definitions[$key]['mapping']['label_display'] = [
          'type' => 'string',
          'label' => 'Label display',
        ];
      }
    }
  }
}
