<?php

/**
* @file
* Install, update, and uninstall functions for Neo Alchemist.
*
* @ingroup neo_alchemist
*/

/**
* Resave all components to support shape to ref changes.
*/
function neo_alchemist_update_11001() {
  /** @var \Drupal\neo_alchemist\ComponentInterface[] $components */
  $components = \Drupal::entityTypeManager()->getStorage('neo_component')->loadMultiple();
  foreach ($components as $component) {
    $component->save();
  }
}
