field.field.*.*.*.third_party.neo_alchemist_taxonomy:
  type: mapping
  label: 'Alchemist taxonomy settings'
  mapping:
    level:
      type: integer
      label: 'Term hierarchy level'

neo_alchemist.neo_component_value.taxonomy_menu:
  type: mapping
  label: 'Taxonomy menu value provider'
  mapping:
    vocabulary:
      type: string
      label: 'Vocabulary'
    root:
      type: integer
      label: 'Root term'
    depth:
      type: integer
      label: 'Number of levels'
    description_field:
      type: string
      label: 'Description field'
    icon_field:
      type: string
      label: 'Icon field'
    processing_mode:
      type: string
      label: 'Processing mode'

neo_alchemist.neo_component_value.taxonomy_children:
  type: mapping
  label: 'Child terms value provider'
  mapping:
    shape_fields:
      type: neo_alchemist.neo_component_shape_fields
    shape_published:
      type: boolean
      label: Shape published
    processing_mode:
      type: string
      label: 'Processing mode'

neo_alchemist.neo_component_value.taxonomy_siblings:
  type: mapping
  label: 'Sibling terms value provider'
  mapping:
    shape_fields:
      type: neo_alchemist.neo_component_shape_fields
    shape_published:
      type: boolean
      label: Shape published
    exclude_self:
      type: boolean
      label: 'Exclude the current term'
    processing_mode:
      type: string
      label: 'Processing mode'
