neo_alchemist.neo_component.*:
  type: config_entity
  label: Component
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
    component:
      type: string
      label: 'Single-Directory Component'
      constraints:
        NotBlank: []
        Regex:
          pattern: '/^[a-z0-9_-]+:[a-z0-9_-]+$/'
          message: 'The %value machine name is not valid.'
        PluginExists:
          manager: plugin.manager.sdc
          interface: 'Drupal\Core\Plugin\PluginBase'
    settings:
      type: mapping
      label: Settings
      mapping:
        props:
          type: neo_alchemist.neo_component_settings.props
      # type: mapping
      # label: Settings
      # mapping:
      #   props:
      #     type: sequence
      #     label: 'Props'
      #     sequence:
      #       type: mapping
      #       label: 'Prop'
      #       mapping:
      #         prop:
      #           type: string
      #           label: Prop
      #         field_type:
      #           type: string
      #           label: 'Default field type'
      #           constraints:
      #             PluginExists:
      #               manager: plugin.manager.field.field_type
      #               interface: '\Drupal\Core\Field\FieldItemInterface'
      #         providers:
      #           type: sequence
      #           label: Providers
      #           sequence:
      #             type: mapping
      #             label: Provider
      #             mapping:
      #               plugin:
      #                 type: string
      #                 label: 'Value provider'
      #                 constraints:
      #                   Regex:
      #                     pattern: '/^[a-z0-9_-]+$/'
      #                     message: 'The %value machine name is not valid.'
      #                   PluginExists:
      #                     manager: plugin.manager.neo_component_value_provider
      #                     interface: '\Drupal\neo_alchemist\ComponentValueProviderPluginInterface'
      #               settings:
      #                 type: neo_alchemist.neo_component_value_provider.[%parent.plugin]
      #                 nullable: true
      # sequence:
      #   type: mapping
      #   mapping:
      #     plugin:
      #       type: string
      #       label: 'Value provider'
      #       constraints:
      #         Regex:
      #           pattern: '/^[a-z0-9_-]+:[a-z0-9_-]+$/'
      #           message: 'The %value machine name is not valid.'
      #         PluginExists:
      #           manager: plugin.manager.neo_component_value_provider
      #           interface: '\Drupal\neo_alchemist\ComponentValueProviderPluginInterface'
      #     field_type:
      #       type: string
      #       label: 'Default field type'
      #       constraints:
      #         PluginExists:
      #           manager: plugin.manager.field.field_type
      #           interface: '\Drupal\Core\Field\FieldItemInterface'
      #     settings:
      #       type: neo_alchemist.neo_component_value_provider.[%parent.plugin]
      #       # type: sequence
      #       # label: 'Value provider settings'
      #       # sequence: neo_alchemist.neo_component_value_provider.[%parent.plugin]
      #       # nullable: true
    target_entity_type:
      type: string
      label: 'Target Entity Type'
    target_entity_bundle:
      type: string
      label: 'Target Entity Bundle'
    # defaults:
    #   type: mapping
    #   mapping:
    #     props:
    #       type: sequence
    #       orderby: key
    #       sequence:
    #         type: mapping
    #         mapping:
    #           field_type:
    #             type: string
    #             label: 'Default field type'
    #             constraints:
    #               PluginExists:
    #                 manager: plugin.manager.field.field_type
    #                 interface: '\Drupal\Core\Field\FieldItemInterface'
    #           value:
    #             type: sequence
    #             label: 'Default values'
    #             sequence:
    #               type: field.value.[%parent.%parent.field_type]
  # constraints:
  #   FullyValidatable: ~

# neo_alchemist.neo_component_value_provider.*:
#   type: neo_component_value_provider

# neo_component_value_provider:
#   type: mapping
#   label: 'Block settings'
#   mapping:
#     id:
#       type: machine_name
#       label: 'ID'
#       constraints:
#         Regex:
#           pattern: '/^[a-z0-9_.]+$/'
#           message: "The %value machine name is not valid."
#     field_type:
#       type: string
#       label: 'Default field type'
#       constraints:
#         PluginExists:
#           manager: plugin.manager.field.field_type
#           interface: '\Drupal\Core\Field\FieldItemInterface'

# neo_alchemist.neo_component_settings:
#   type: mapping
#   label: Settings
#   mapping:
#     props:
#       type: sequence
#       label: 'Props'
#       sequence:
#         type: mapping
#         label: 'Prop'
#         mapping:
#           prop:
#             type: string
#             label: Prop
#           field_type:
#             type: string
#             label: 'Default field type'
#             constraints:
#               PluginExists:
#                 manager: plugin.manager.field.field_type
#                 interface: '\Drupal\Core\Field\FieldItemInterface'
#           providers:
#             type: sequence
#             label: Providers
#             sequence:
#               type: mapping
#               label: Provider
#               mapping:
#                 plugin:
#                   type: string
#                   label: 'Value provider'
#                   constraints:
#                     Regex:
#                       pattern: '/^[a-z0-9_-]+$/'
#                       message: 'The %value machine name is not valid.'
#                     PluginExists:
#                       manager: plugin.manager.neo_component_value_provider
#                       interface: '\Drupal\neo_alchemist\ComponentValueProviderPluginInterface'
#                 settings:
#                   type: neo_alchemist.neo_component_value_provider.[%parent.plugin]
#                   nullable: true

neo_alchemist.neo_component_settings.props:
  type: sequence
  label: 'Props'
  sequence:
    type: mapping
    label: 'Prop'
    mapping:
      prop:
        type: string
        label: Prop
      field_type:
        type: string
        label: 'Default field type'
        constraints:
          PluginExists:
            manager: plugin.manager.field.field_type
            interface: '\Drupal\Core\Field\FieldItemInterface'
      editable:
        type: boolean
        title: Editable
      providers:
        type: sequence
        label: Providers
        sequence:
          type: mapping
          label: Provider
          mapping:
            plugin:
              type: string
              label: 'Value provider'
              constraints:
                Regex:
                  pattern: '/^[a-z0-9_-]+$/'
                  message: 'The %value machine name is not valid.'
                PluginExists:
                  manager: plugin.manager.neo_component_value_provider
                  interface: '\Drupal\neo_alchemist\ComponentValueProviderPluginInterface'
            settings:
              type: neo_alchemist.neo_component_value_provider.[%parent.plugin]
              nullable: true


neo_alchemist.neo_component_value_provider.*:
  type: mapping

neo_alchemist.neo_component_value_provider.default:
  type: mapping
  label: 'Default value provider'
  mapping:
    default:
      type: field.value.[%parent.%parent.%parent.%parent.field_type]

neo_alchemist.neo_component_value_provider.entity:
  type: mapping
  label: 'Default value provider'
  mapping:
    field:
      type: string
      label: 'The field to get the value from'
    override:
      type: boolean
      label: 'Allow override when value is found'
    override_empty:
      type: boolean
      label: 'Allow override when value is empty'
