neo_alchemist.neo_component.*:
  type: config_entity
  label: Component
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
    component:
      type: string
      label: 'Single-Directory Component'
      constraints:
        NotBlank: []
        Regex:
          pattern: '/^[a-z0-9_-]+:[a-z0-9_-]+$/'
          message: 'The %value machine name is not valid.'
        PluginExists:
          manager: plugin.manager.sdc
          interface: 'Drupal\Core\Plugin\PluginBase'
    settings:
      type: mapping
      label: Settings
      mapping:
        props:
          type: neo_alchemist.neo_component_settings.props
    target_entity_type:
      type: string
      label: 'Target Entity Type'
    target_entity_bundle:
      type: string
      label: 'Target Entity Bundle'

neo_alchemist.neo_component_settings.props:
  type: sequence
  label: 'Props'
  sequence:
    type: mapping
    label: 'Prop'
    mapping:
      prop:
        type: string
        label: Prop
      shape:
        type: string
        label: 'Shape ID'
        constraints:
          PluginExists:
            manager: plugin.manager.neo_component_shape
            interface: '\Drupal\neo_alchemist\ComponentShapePluginInterface'
      field_type:
        type: string
        label: 'Default field type'
        constraints:
          PluginExists:
            manager: plugin.manager.field.field_type
            interface: '\Drupal\Core\Field\FieldItemInterface'
      editable:
        type: boolean
        title: Editable
      required:
        type: boolean
        title: Required
      providers:
        type: sequence
        label: Providers
        sequence:
          type: mapping
          label: Provider
          mapping:
            plugin:
              type: string
              label: 'Value provider'
              constraints:
                Regex:
                  pattern: '/^[a-z0-9_-]+$/'
                  message: 'The %value machine name is not valid.'
                PluginExists:
                  manager: plugin.manager.neo_component_value_provider
                  interface: '\Drupal\neo_alchemist\ComponentValueProviderPluginInterface'
            settings:
              type: neo_alchemist.neo_component_value_provider.[%parent.plugin]
              nullable: true
      modifiers:
        type: sequence
        label: Modifiers
        sequence:
          type: mapping
          label: Modifier
          mapping:
            plugin:
              type: string
              label: 'Value modifier'
              constraints:
                Regex:
                  pattern: '/^[a-z0-9_-]+$/'
                  message: 'The %value machine name is not valid.'
                PluginExists:
                  manager: plugin.manager.neo_component_value_modifier
                  interface: '\Drupal\neo_alchemist\ComponentValueModifierPluginInterface'
            settings:
              type: neo_alchemist.neo_component_value_modifier.[%parent.plugin]
              nullable: true

neo_alchemist.neo_component_value_provider.*:
  type: mapping

neo_alchemist.neo_component_value_provider.default:
  type: mapping
  label: 'Default value provider'
  mapping:
    default:
      type: field.value.[%parent.%parent.%parent.%parent.field_type]
      mapping:
        _hide:
          type: boolean
          label: 'If value is set as hidden'

neo_alchemist.neo_component_value_provider.entity:
  type: mapping
  label: 'Default value provider'
  mapping:
    field:
      type: string
      label: 'The field to get the value from'
    override:
      type: boolean
      label: 'Allow override when value is found'
    override_empty:
      type: boolean
      label: 'Allow override when value is empty'

neo_alchemist.neo_component_value_modifier.*:
  type: mapping

neo_alchemist.neo_component_value_modifier.prefix:
  type: mapping
  label: 'Prefix value modifier'
  mapping:
    value:
      label: Prefix
      type: string

neo_alchemist.neo_component_value_modifier.suffix:
  type: mapping
  label: 'Suffix value modifier'
  mapping:
    value:
      label: Suffix
      type: string

neo_alchemist.neo_component_value_modifier.number:
  type: mapping
  label: 'Convert value to number'
  mapping:
    decimals:
      label: Decimals
      type: integer
      constraints:
        NotNull: []
        Range:
          min: 0
    decimal_separator:
      label: Decimal Separator
      type: string
    thousands_separator:
      label: Thousands Separator
      type: string
