neo_alchemist.neo_component.*:
  type: config_entity
  label: Component
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
    expression:
      type: string
      label: 'Expression'
    schema:
      type: string
      label: 'Schema'
    thumbnail:
      type: string
      label: 'Thumbnail'
    component:
      type: string
      label: 'Single-Directory Component'
      constraints:
        NotBlank: []
        Regex:
          pattern: '/^[a-z0-9_-]+:[a-z0-9_-]+$/'
          message: 'The %value machine name is not valid.'
        PluginExists:
          manager: plugin.manager.sdc
          interface: 'Drupal\Core\Plugin\PluginBase'
    settings:
      type: mapping
      label: Settings
      mapping:
        props:
          type: neo_alchemist.neo_component_settings.props
    target_entity_type:
      type: string
      label: 'Target Entity Type'
    target_entity_bundle:
      type: string
      label: 'Target Entity Bundle'

neo_alchemist.neo_component_settings.props:
  type: sequence
  label: 'Props'
  sequence:
    type: mapping
    label: 'Prop'
    mapping:
      prop:
        type: string
        label: Prop
      shape:
        type: string
        label: 'Shape ID'
        constraints:
          PluginExists:
            manager: plugin.manager.neo_component_shape
            interface: '\Drupal\neo_alchemist\ComponentShapePluginInterface'
      field_type:
        type: string
        label: 'Default field type'
        constraints:
          PluginExists:
            manager: plugin.manager.field.field_type
            interface: '\Drupal\Core\Field\FieldItemInterface'
      editable:
        type: boolean
        title: Editable
      required:
        type: boolean
        title: Required
      expanded:
        type: sequence
        title: Expanded
        sequence:
          type: string
          label: Nested ID
      plugins:
        type: sequence
        label: Plugins
        sequence:
          type: sequence
          label: Nested ID
          sequence:
            type: mapping
            label: Plugin
            mapping:
              id:
                type: string
                label: 'Value Plugin'
                constraints:
                  Regex:
                    pattern: '/^[a-z0-9_-]+$/'
                    message: 'The %value machine name is not valid.'
                  PluginExists:
                    manager: plugin.manager.neo_component_value
                    interface: '\Drupal\neo_alchemist\ComponentValuePluginInterface'
              settings:
                type: neo_alchemist.neo_component_value.[%parent.id]
                nullable: true

neo_alchemist.neo_component_value.*:
  type: mapping

neo_alchemist.neo_component_value.default:
  type: mapping
  label: 'Default value provider'
  mapping:
    default:
      type: field.value.[%parent.%parent.%parent.%parent.%parent.field_type]
    options:
      type: mapping
      label: Options
      mapping:
        empty:
          type: boolean
          label: Treat value as empty
        default:
          type: boolean
          label: Treat value as default

neo_alchemist.neo_component_value.entity:
  type: mapping
  label: 'Default value provider'
  mapping:
    field:
      type: string
      label: 'The field to get the value from'
    override:
      type: boolean
      label: 'Allow override when value is found'
    override_empty:
      type: boolean
      label: 'Allow override when value is empty'

neo_alchemist.neo_component_value.media:
  type: mapping
  label: 'Default value provider'
  mapping:
    default:
      type: sequence
      label: Defaults
      nullable: true
      sequence:
        type: string
        label: 'Config File'

neo_alchemist.neo_component_value.prefix:
  type: mapping
  label: 'Prefix value modifier'
  mapping:
    value:
      label: Prefix
      type: string

neo_alchemist.neo_component_value.suffix:
  type: mapping
  label: 'Suffix value modifier'
  mapping:
    value:
      label: Suffix
      type: string

neo_alchemist.neo_component_value.number:
  type: mapping
  label: 'Convert value to number'
  mapping:
    decimals:
      label: Decimals
      type: integer
      constraints:
        NotNull: []
        Range:
          min: 0
    decimal_separator:
      label: Decimal Separator
      type: string
    thousands_separator:
      label: Thousands Separator
      type: string
