<?php

declare(strict_types=1);

namespace Drupal\neo_alchemist\Plugin\DataType;

use Drupal\Core\Cache\CacheableDependencyInterface;
use Drupal\Core\Cache\CacheableJsonResponse;
use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Entity\Plugin\DataType\EntityAdapter;
use Drupal\Core\Render\RenderableInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Template\Attribute;
use Drupal\Core\TypedData\Attribute\DataType;
use Drupal\Core\TypedData\TypedData;
use Drupal\neo_alchemist\Plugin\Field\FieldType\ComponentTreeItem;

/**
 * Hydrated data.
 */
#[DataType(
  id: "neo_component_tree_hydrated",
  label: new TranslatableMarkup("Hydrated component tree"),
  description: new TranslatableMarkup("Computed from tree structure + props values"),
)]
class ComponentTreeHydrated extends TypedData implements CacheableDependencyInterface, RenderableInterface {

  /**
   * The computed value.
   *
   * @var mixed
   */
  protected mixed $value;

  /**
   * {@inheritdoc}
   */
  public function getValue(): CacheableJsonResponse {
    $item = $this->getParent();
    assert($item instanceof ComponentTreeItem);
    $tree = $item->get('tree');
    assert($tree instanceof ComponentTreeStructure);

    $hydrated = [];
    foreach ($tree->getComponentInstanceUuids() as $uuid) {
      $component_id = $tree->getComponentId($uuid);
      $props = $item->resolveComponentProps($uuid);
      $instance = $item->getComponent($uuid);
      if (!$instance) {
        continue;
      }
      // We allow unpublished components to be rendered, but only if we are
      // in draft mode.
      if ($instance->isPublished() || $instance->getFieldItem()->isDraft()) {
        $component = $instance->getComponent();
        if ($component) {
          $hydrated[$uuid] = [
            'neo_component' => $component_id,
            'component' => $component->getPluginId(),
            'props' => $props,
          ];
          $hydrated[$uuid]['props'] = $this->convertValuesToAttributePlaceholder($hydrated[$uuid]['props']);
          if (!empty($component->metadata->slots)) {
            $defaultSlotValue = array_map(
              fn (array $s): string => self::getDefaultSlotValue($s),
              $component->metadata->slots,
            );
            $hydrated[$uuid]['slots'] = $defaultSlotValue;
          }
        }
      }
    }

    // Transform the flat list of hydrated components into a hydrated component
    // tree, by assigning child components to their parent component's slot. If
    // this happens depth-first, then the tree will gradually be built, with the
    // last iteration assigning the last component to the component tree's root.
    foreach ($tree->getSlotChildrenDepthFirst() as $parent_uuid => [
      'slot' => $slot,
      'uuid' => $uuid,
    ]) {
      assert(array_key_exists('slots', $hydrated[$parent_uuid]));

      // Remove default slot value: this slot is populated.
      if (is_string($hydrated[$parent_uuid]['slots'][$slot])) {
        unset($hydrated[$parent_uuid]['slots'][$slot]);
      }

      $hydrated[$parent_uuid]['slots'][$slot][$uuid] = $hydrated[$uuid];
      unset($hydrated[$uuid]);
    }

    return (new CacheableJsonResponse())
      ->addCacheableDependency($this->getCacheability())
      ->setData([ComponentTreeStructure::ROOT_UUID => $hydrated]);
  }

  /**
   * {@inheritdoc}
   */
  public function setValue($value, $notify = TRUE): void {
    // There is nothing to set, so return early.
    // @todo This is an upstream core bug, because this is defined as both
    // computed and read-only, yet it still gets called 🙃 Once the core bug is
    // fixed, this should throw a ReadOnlyException.
    // throw new ReadOnlyException();
  }

  /**
   * {@inheritdoc}
   */
  public function toRenderable(): array {
    $renderable_component_tree = $this->getValue();

    $build = [];
    // @see \Drupal\Core\Entity\EntityViewBuilder::getBuildDefaults()
    $renderable_component_tree->getCacheableMetadata()->applyTo($build);

    $json = $renderable_component_tree->getContent();
    assert(is_string($json));
    $hydrated = json_decode($json, TRUE);

    assert(array_keys($hydrated) === [ComponentTreeStructure::ROOT_UUID]);
    return self::renderify($hydrated);
  }

  /**
   * Recursively converts an array generated by ::getValue() to a render array.
   *
   * @param array $hydrated
   *   An array generated by ::getValue().
   *
   * @return array
   *   The corresponding render array.
   */
  private static function renderify(array $hydrated) {
    $build = [];
    foreach ($hydrated as $component_subtree_uuid => $component_instances) {
      foreach ($component_instances as $component_instance_uuid => $component_instance) {
        $build[$component_subtree_uuid][$component_instance_uuid] = [
          '#type' => 'component',
          '#cache' => [
            'tags' => [
              'config:neo_alchemist.component.' . $component_instance['neo_component'],
            ],
          ],
        ];
        foreach ($component_instance as $key => $value) {
          if ($key !== 'slots') {
            if ($key === 'props') {
              $value = self::convertAttributePlaceholderToAttribute($value);
            }
            // Note: this works because `::getValue()` above uses `props` and
            // `slots`, which allow simply prefixing them with `#` to generate the
            // corresponding render array.
            $build[$component_subtree_uuid][$component_instance_uuid]["#$key"] = $value;
            continue;
          }

          $attributes = new Attribute();
          if (!empty($build[$component_subtree_uuid][$component_instance_uuid]['#props']['attributes'])) {
            // Add passed in attributes to an Attribute object.
            $attributes->merge(new Attribute($build[$component_subtree_uuid][$component_instance_uuid]['#props']['attributes']));
          }
          $build[$component_subtree_uuid][$component_instance_uuid]['#props']['attributes'] = $attributes;

          $build[$component_subtree_uuid][$component_instance_uuid]["#slots"] = [];
          foreach ($value as $slot => $slot_value) {
            // Handle default slot value: convert to renderable using either
            // #plain_text or `#markup`.
            if (is_string($slot_value)) {
              $build[$component_subtree_uuid][$component_instance_uuid]["#slots"][$slot] = !str_starts_with($slot_value, '<')
                // Match how Drupal core handles string values for components.
                // @see https://www.drupal.org/node/3398039
                ? ['#plain_text' => $slot_value]
                // TRICKY: this goes beyond what Drupal core appears to allow
                // in https://www.drupal.org/node/3398039, but the SDC plugin
                // manager accepts this as a valid SDC definition, so XB has
                // no choice but to support it.
                : ['#markup' => $slot_value];
            }
            // Explicit slot value: renderify, just like the rest of the
            // component tree.
            else {
              $build[$component_subtree_uuid][$component_instance_uuid]["#slots"] += self::renderify([$slot => $slot_value]);
            }
          }
        }
      }
    }
    return $build;
  }

  /**
   * Converts values to attributes.
   *
   * @param array $values
   *   The prop values.
   *
   * @return array
   *   The prop values with attributes converted to arrays.
   */
  private function convertValuesToAttributePlaceholder(array $values) {
    foreach ($values as $key => $value) {
      if ($value instanceof Attribute) {
        $values[$key] = [
          '_attribute' => $value->toArray(),
        ];
      }
      elseif (is_array($value)) {
        $values[$key] = $this->convertValuesToAttributePlaceholder($value);
      }
    }
    return $values;
  }

  /**
   * Converts attribute placeholders to attributes.
   *
   * @param array $values
   *   The prop values.
   *
   * @return array
   *   The prop values with attributes converted to arrays.
   */
  private static function convertAttributePlaceholderToAttribute(array $values) {
    foreach ($values as $key => $value) {
      if (is_array($value) && array_key_exists('_attribute', $value)) {
        $values[$key] = new Attribute($value['_attribute']);
      }
      elseif (is_array($value)) {
        $values[$key] = self::convertAttributePlaceholderToAttribute($value);
      }
    }
    return $values;
  }

  /**
   * Computes the cacheability of this computed property.
   *
   * @return \Drupal\Core\Cache\CacheableMetadata
   *   The cacheability of the computed value.
   */
  private function getCacheability(): CacheableMetadata {
    $root = $this->getRoot();
    if ($root instanceof EntityAdapter) {
      return CacheableMetadata::createFromObject($root->getEntity());
    }
    // This appears to be an ephemeral component tree, hence it is uncacheable.
    return (new CacheableMetadata())->setCacheMaxAge(0);
  }

  /**
   * {@inheritdoc}
   */
  public function getCacheTags() {
    return $this->getCacheability()->getCacheTags();
  }

  /**
   * {@inheritdoc}
   */
  public function getCacheContexts() {
    return $this->getCacheability()->getCacheContexts();
  }

  /**
   * {@inheritdoc}
   */
  public function getCacheMaxAge() {
    return $this->getCacheability()->getCacheMaxAge();
  }

  /**
   * Get default slot value.
   *
   * @param array $slot_schema
   *   The slot schema.
   */
  private static function getDefaultSlotValue(array $slot_schema): string {
    if (array_key_exists('examples', $slot_schema) && array_key_exists(0, $slot_schema['examples'])) {
      return $slot_schema['examples'][0];
    }
    return '';
  }

}
