<?php

declare(strict_types=1);

namespace Drupal\neo_alchemist\Plugin\DataType;

use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Entity\Plugin\DataType\EntityAdapter;
use Drupal\Core\Render\RenderableInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\TypedData\Attribute\DataType;
use Drupal\Core\TypedData\TypedData;
use Drupal\neo_alchemist\ComponentShapeRegionPluginInterface;
use Drupal\neo_alchemist\Plugin\Field\FieldType\ComponentTreeItem;

/**
 * Hydrated data.
 */
#[DataType(
  id: "neo_component_tree_hydrated",
  label: new TranslatableMarkup("Hydrated component tree"),
  description: new TranslatableMarkup("Computed from tree structure + props values"),
)]
class ComponentTreeHydrated extends TypedData implements RenderableInterface {

  /**
   * The computed value.
   *
   * @var mixed
   */
  protected mixed $value;

  /**
   * {@inheritdoc}
   */
  public function getValue(): array {
    $item = $this->getParent();
    assert($item instanceof ComponentTreeItem);
    $tree = $item->get('tree');
    assert($tree instanceof ComponentTreeStructure);

    $hydrated = [];
    foreach ($tree->getComponentInstanceUuids() as $key => $uuid) {
      $instance = $item->getComponent($uuid);
      if (!$instance) {
        // Component no longer exists.
        continue;
      }
      // We allow unpublished components to be rendered, but only if we are
      // in draft mode.
      if ($instance->isPublished() || $instance->getFieldItem()->isDraft()) {
        $hydrated[$uuid] = [];
        if ($slots = $instance->getComponentSlots()) {
          $hydrated[$uuid]['slots'] = array_map(fn($slot) => $slot['examples'][0] ?? '', $slots);
        }

        $shapes = $instance->getPropShapesAll(NULL, TRUE);
        // Treat region shapes as slots.
        foreach ($shapes as $shapeName => $shape) {
          if ($shape instanceof ComponentShapeRegionPluginInterface) {
            $hydrated[$uuid]['slots'][$shape->id()] = [];
          }
        }
      }
    }

    // Transform the flat list of hydrated components into a hydrated component
    // tree, by assigning child components to their parent component's slot. If
    // this happens depth-first, then the tree will gradually be built, with the
    // last iteration assigning the last component to the component tree's root.
    foreach ($tree->getSlotChildrenDepthFirst() as $parent_uuid => [
      'slot' => $slot,
      'uuid' => $uuid,
    ]) {
      assert(array_key_exists('slots', $hydrated[$parent_uuid]));

      // Remove default slot value: this slot is populated.
      if (isset($hydrated[$parent_uuid]['slots']) && is_string($hydrated[$parent_uuid]['slots'][$slot])) {
        unset($hydrated[$parent_uuid]['slots'][$slot]);
      }
      $hydrated[$parent_uuid]['slots'][$slot][$uuid] = $hydrated[$uuid] ?? [];
      unset($hydrated[$uuid]);
    }

    return [ComponentTreeStructure::ROOT_UUID => $hydrated];
  }

  /**
   * {@inheritdoc}
   */
  public function setValue($value, $notify = TRUE): void {
    // There is nothing to set, so return early.
    // @todo This is an upstream core bug, because this is defined as both
    // computed and read-only, yet it still gets called once the core bug is
    // fixed, this should throw a ReadOnlyException.
    // throw new ReadOnlyException();
  }

  /**
   * {@inheritdoc}
   */
  public function toRenderable(): array {
    $item = $this->getParent();
    assert($item instanceof ComponentTreeItem);

    $hydrated = $this->getValue();
    $cacheableMetadata = $this->getCacheability();
    $build = $this->renderify($hydrated, $cacheableMetadata);
    $cacheableMetadata->applyTo($build);
    return $build;
  }

  /**
   * Recursively converts an array generated by ::getValue() to a render array.
   *
   * @todo Add recursive slots.
   *
   * @param array $hydrated
   *   An array generated by ::getValue().
   * @param \Drupal\Core\Cache\CacheableMetadata $cacheableMetadata
   *   The cacheability of the computed value.
   *
   * @return array
   *   The corresponding render array.
   */
  private function renderify(array $hydrated, CacheableMetadata $cacheableMetadata) {
    $item = $this->getParent();
    assert($item instanceof ComponentTreeItem);

    $build = [];
    foreach ($hydrated as $component_subtree_uuid => $component_instances) {
      foreach ($component_instances as $component_instance_uuid => $component_instance) {
        $instance = $item->getComponent($component_instance_uuid);
        $cacheableMetadata->addCacheableDependency($instance);
        if (!$instance->access('view')) {
          // Skip components that are not accessible.
          continue;
        }
        if (!empty($component_instance['slots'])) {
          $shapes = $instance->getPropShapesAll(NULL, TRUE);
          foreach ($component_instance['slots'] as $slot => $children) {
            $shape = $shapes[$slot] ?? NULL;
            if ($shape instanceof ComponentShapeRegionPluginInterface) {
              // When we have slot values for a shape that acts as a region, we
              // pass these as values to the region shape.
              $shape->setFieldItemValue(array_keys($children));
            }
          }
        }
        // $instance->getPropShapes();
        $build[$component_subtree_uuid][$component_instance_uuid] = $instance->toRenderable();
      }
    }
    return $build;
  }

  /**
   * Computes the cacheability of this computed property.
   *
   * @return \Drupal\Core\Cache\CacheableMetadata
   *   The cacheability of the computed value.
   */
  private function getCacheability(): CacheableMetadata {
    $root = $this->getRoot();
    if ($root instanceof EntityAdapter) {
      return CacheableMetadata::createFromObject($root->getEntity());
    }
    // This appears to be an ephemeral component tree, hence it is uncacheable.
    return (new CacheableMetadata())->setCacheMaxAge(0);
  }

}
