<?php

declare(strict_types=1);

namespace Drupal\neo_alchemist\Plugin\DataType;

use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Entity\Plugin\DataType\EntityAdapter;
use Drupal\Core\Render\RenderableInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\TypedData\Attribute\DataType;
use Drupal\Core\TypedData\TypedData;
use Drupal\neo_alchemist\ComponentFieldConfigInterface;
use Drupal\neo_alchemist\Shape\ComponentShapeRegionPluginInterface;
use Drupal\neo_alchemist\Plugin\Field\FieldType\ComponentTreeItem;

/**
 * Hydrated data.
 */
#[DataType(
  id: "neo_component_tree_hydrated",
  label: new TranslatableMarkup("Hydrated component tree"),
  description: new TranslatableMarkup("Computed from tree structure + props values"),
)]
class ComponentTreeHydrated extends TypedData implements RenderableInterface {

  /**
   * The computed value.
   *
   * @var mixed
   */
  protected mixed $value;

  /**
   * {@inheritdoc}
   */
  public function getValue(): array {
    $item = $this->getParent();
    assert($item instanceof ComponentTreeItem);
    $tree = $item->get('tree');
    assert($tree instanceof ComponentTreeStructure);

    $hydrated = [];
    foreach ($tree->getComponentInstanceUuids() as $uuid) {
      $instance = $item->getComponent($uuid);
      if (!$instance) {
        // Component no longer exists. Skipping is the only safe thing to do —
        // renderify() below re-resolves each uuid unguarded, so keeping this
        // one to render a placeholder would fatal — but skipping silently is
        // what makes a renamed or deleted component look like an empty page
        // with nothing wrong. Say so instead.
        //
        // Only this branch logs. The published check below filters unpublished
        // components too, and that is routine, not a fault.
        self::logMissingComponent($item, $uuid);
        continue;
      }
      // We allow unpublished components to be rendered, but only if we are
      // in draft mode.
      if ($instance->isPublished() || $instance->getFieldItem()->isDraft()) {
        $hydrated[$uuid] = [];
        if ($slots = $instance->getComponentSlots()) {
          $hydrated[$uuid]['slots'] = array_map(fn($slot) => $slot['examples'][0] ?? '', $slots);
        }

        $shapes = $instance->getPropShapesAll(NULL, TRUE);
        // Treat region shapes as slots.
        foreach ($shapes as $shape) {
          if ($shape instanceof ComponentShapeRegionPluginInterface) {
            $hydrated[$uuid]['slots'][$shape->id()] = [];
          }
        }
      }
    }

    // Transform the flat list of hydrated components into a hydrated component
    // tree, by assigning child components to their parent component's slot. If
    // this happens depth-first, then the tree will gradually be built, with the
    // last iteration assigning the last component to the component tree's root.
    foreach ($tree->getSlotChildrenDepthFirst() as $parent_uuid => [
      'slot' => $slot,
      'uuid' => $uuid,
    ]) {
      if (!isset($hydrated[$parent_uuid])) {
        // This component's parent does not exist, likely because it is
        // unpublished or the component was deleted and we are not in draft
        // mode, so we skip it and all of its children. We also remove it from
        // the hydrated list to avoid leaving orphaned components in the final
        // tree.
        unset($hydrated[$uuid]);
        continue;
      }
      assert(array_key_exists('slots', $hydrated[$parent_uuid]));

      // Remove default slot value: this slot is populated. The $slot key is
      // guarded — a stored tree can reference a slot the component no longer
      // declares, and that must not warn its way into a failure.
      if (is_string($hydrated[$parent_uuid]['slots'][$slot] ?? NULL)) {
        unset($hydrated[$parent_uuid]['slots'][$slot]);
      }
      $hydrated[$parent_uuid]['slots'][$slot][$uuid] = $hydrated[$uuid] ?? [];
      unset($hydrated[$uuid]);
    }

    return [ComponentTreeStructure::ROOT_UUID => $hydrated];
  }

  /**
   * {@inheritdoc}
   */
  public function setValue($value, $notify = TRUE): void {
    // There is nothing to set, so return early.
    // @todo This is an upstream core bug, because this is defined as both
    // computed and read-only, yet it still gets called once the core bug is
    // fixed, this should throw a ReadOnlyException.
    // throw new ReadOnlyException();
  }

  /**
   * {@inheritdoc}
   */
  public function toRenderable(): array {
    $item = $this->getParent();
    assert($item instanceof ComponentTreeItem);

    $hydrated = $this->getValue();
    $cacheableMetadata = $this->getCacheability();
    $build = $this->renderify($hydrated, $cacheableMetadata);
    $cacheableMetadata->applyTo($build);
    return $build;
  }

  /**
   * Recursively converts an array generated by ::getValue() to a render array.
   *
   * @todo Add recursive slots.
   *
   * @param array $hydrated
   *   An array generated by ::getValue().
   * @param \Drupal\Core\Cache\CacheableMetadata $cacheableMetadata
   *   The cacheability of the computed value.
   *
   * @return array
   *   The corresponding render array.
   */
  private function renderify(array $hydrated, CacheableMetadata $cacheableMetadata) {
    $item = $this->getParent();
    assert($item instanceof ComponentTreeItem);

    $build = [];
    foreach ($hydrated as $component_subtree_uuid => $component_instances) {
      // Resolve and access-filter before deciding anything about position. A
      // component is first or last among the ones that actually render, not
      // among the ones that were stored — taking the ends of the unfiltered
      // list offered a dead Move Up whenever the leading sibling was hidden.
      $renderable = [];
      foreach ($component_instances as $component_instance_uuid => $component_instance) {
        $instance = $item->getComponent($component_instance_uuid);
        $cacheableMetadata->addCacheableDependency($instance);
        // Capture the access decision's cacheability (e.g. value-provider list
        // or entity tags) so a hidden component is re-evaluated when its
        // dependencies change. Boolean mode would discard this metadata.
        $accessResult = $instance->access('view', NULL, TRUE);
        $cacheableMetadata->addCacheableDependency($accessResult);
        if (!$accessResult->isAllowed()) {
          // Skip components that are not accessible.
          continue;
        }
        $renderable[$component_instance_uuid] = $instance;
      }
      $uuids = array_keys($renderable);
      $first = reset($uuids);
      $last = end($uuids);
      foreach ($renderable as $component_instance_uuid => $instance) {
        $component_instance = $component_instances[$component_instance_uuid];
        if (!empty($component_instance['slots'])) {
          $shapes = $instance->getPropShapesAll(NULL, TRUE);
          foreach ($component_instance['slots'] as $slot => $children) {
            $shape = $shapes[$slot] ?? NULL;
            if ($shape instanceof ComponentShapeRegionPluginInterface) {
              // When we have slot values for a shape that acts as a region, we
              // pass these as values to the region shape.
              $shape->setFieldItemValue(array_keys($children));
            }
          }
        }
        $isFirst = $first === $component_instance_uuid;
        $isLast = $last === $component_instance_uuid;
        $build[$component_subtree_uuid][$component_instance_uuid] = $instance->toRenderable($isFirst, $isLast);
      }
    }
    return $build;
  }

  /**
   * Computes the cacheability of this computed property.
   *
   * @return \Drupal\Core\Cache\CacheableMetadata
   *   The cacheability of the computed value.
   */
  private function getCacheability(): CacheableMetadata {
    $root = $this->getRoot();
    if ($root instanceof EntityAdapter) {
      $cacheability = CacheableMetadata::createFromObject($root->getEntity());
      // The rendered tree also depends on the field config: the field default
      // layout (and its custom-region anchors) lives there, so a site
      // builder's default-layout change must invalidate rendered entities.
      $item = $this->getParent();
      if ($item instanceof ComponentTreeItem) {
        $definition = $item->getFieldDefinition();
        if ($definition instanceof ComponentFieldConfigInterface) {
          $cacheability->addCacheableDependency($definition);
        }
      }
      return $cacheability;
    }
    // This appears to be an ephemeral component tree, hence it is uncacheable.
    return (new CacheableMetadata())->setCacheMaxAge(0);
  }

  /**
   * Logs a tree entry whose component config entity no longer exists.
   *
   * Deduplicated per request: the render path is cache-backed, but a hot
   * uncached page would otherwise write one entry per render per instance, and
   * a warning nobody can read is no better than no warning.
   */
  protected static function logMissingComponent(ComponentTreeItem $item, string $uuid): void {
    static $seen = [];

    $componentId = (string) ($item->get('tree')->getComponentId($uuid) ?? '');
    $host = 'unknown';
    $field = '';
    try {
      $entity = $item->getEntity();
      $host = $entity->getEntityTypeId() . ':' . ($entity->id() ?? 'new');
      $field = $item->getFieldDefinition()->getName();
    }
    catch (\Throwable) {
      // An ephemeral tree with no host entity still deserves the warning; it
      // just cannot say where it came from.
    }

    $key = $host . '|' . $field . '|' . $uuid . '|' . $componentId;
    if (isset($seen[$key])) {
      return;
    }
    $seen[$key] = TRUE;

    \Drupal::logger('neo_alchemist')->warning('Component tree on @host (@field) places "@component", which does not exist. That placement renders nothing. Run `drush neo:alchemist:integrity` to locate it.', [
      '@host' => $host,
      '@field' => $field ?: 'unknown field',
      '@component' => $componentId ?: 'unknown component',
    ]);
  }

}
